name: hoseo_m_client
description: "호서대학교 UI/UX 7조 hose_m client project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.1
  webview_flutter: ^4.4.2
  permission_handler: ^11.0.1
  dio: ^5.8.0
  sqflite: ^2.4.2
  path: ^1.9.1
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # 폰트 설정
  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: fonts/Pretendard-Light.ttf
          weight: 300
        - asset: fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: fonts/Pretendard-Black.ttf
          weight: 900
